/**
 * Every word the studio says, in both languages, except what a tablature file
 * carries: its title, track names and notation are the file's, not ours.
 *
 * English is the shape. French must say everything English says, which the
 * type enforces. Keys follow the component that speaks them.
 *
 * The engine (`engine/`) keeps its own messages in English and carries no
 * language: a message it throws is translated here, by its failure kind or by
 * its exact text, and one this table does not know is shown as it came.
 */

import type { EngineFailure } from '../engine/chain-host.ts';

const en = {
  params: {
    in_trim: 'Input', gate_threshold: 'Gate', out_master: 'Output',
    tone_bass: 'Bass', tone_mid: 'Mid', tone_treble: 'Treble', tone_presence: 'Presence',
    pitch_shift: 'Shift', pitch_mix: 'Mix', drive_gain: 'Gain', drive_tone: 'Color', reverb_mix: 'Mix',
    doubler_spread: 'Doubler',
  } as Record<string, string>,

  rig: {
    globalControls: 'Global controls',
    home: 'Back to the home page',
    modeLabel: 'Mode',
    modes: { tone: 'Tone', play: 'Play' },
    modeTitles: { tone: 'The amp, to dial a tone', play: 'The tab, to play along' },
    transport: 'Transport',
    tab: 'Tab',
    openTab: 'Open a tab',
    bar: 'Bar',
    tracks: 'Tracks',
    practice: 'Practice',
    tools: 'Tools',
    levels: 'Levels',
    tabLevel: 'Tab',
    take: 'Take',
    recordTake: 'Record a take',
    stopTake: 'Stop the take',
    showRecorder: 'Show the takes',
    hideRecorder: 'Hide the takes',
    meterIn: 'In',
    meterOut: 'Out',
    gateEnabled: 'Gate enabled',
    gateOn: 'Gate on',
    gateOff: 'Gate off',
    doublerEnabled: 'Doubler enabled',
    doublerOn: 'Doubler on: a second take in the right ear, up to this many milliseconds behind',
    doublerOff: 'Doubler off: the same guitar in both ears',
    amplifier: 'Amplifier',
    cabinet: 'Cabinet',
    capture: 'Capture',
    cabinetIrFile: 'Cabinet IR file',
    loadIr: 'Load an IR…',
    tonePreset: 'Tone preset',
    customTone: 'Custom tone',
    previousPreset: 'Previous preset',
    nextPreset: 'Next preset',
    presets: { Lead: 'Lead', 'Modern metal': 'Modern metal', Clean: 'Clean' } as Record<string, string>,
    myTones: 'My tones',
    manageTones: 'Manage',
    saveTone: 'Save this tone…',
    deleteTone: (name: string) => `Delete “${name}”`,
    toneName: 'Tone name',
    saveToneConfirm: 'Save',
    replaceTone: 'Replace',
    cancelTone: 'Cancel',
    toneNotKept: 'This browser keeps nothing: the tone will be gone when the page closes.',
    cabs: {
      v30mod: 'V30 4x12 — Modern', v30dark: 'V30 4x12 — Off-Axis', green: 'Greenback 4x12 — Vintage', mod112: '1x12 Open Back',
    } as Record<string, string>,
    guiltAmp: 'GUILT amplifier',
    neutralAmp: 'Tonecraft amplifier',
    glassAlt: 'Purple Gothic stained glass with a central rose window',
    neutralMotto: 'FIND YOUR FREQUENCY',
    leadAmplifier: 'LEAD AMPLIFIER',
    captureSeries: 'CAPTURE SERIES',
    groups: { tone: 'Tone', pitch: 'Pitch', boost: 'Boost', reverb: 'Reverb' },
    groupEnabled: { tone: 'Tone enabled', pitch: 'Pitch enabled', boost: 'Boost enabled', reverb: 'Reverb enabled' },
    /* What a switch says about itself in its tooltip; the state is nowhere on
       the plate, because an engraved plate never says it either. */
    /* The stages the amplifier's plate has no place engraved for. */
    pedals: 'Pedals',
    on: 'On',
    off: 'Off',
    power: 'Power',
    amplifierPower: 'Amplifier power',
    captureSilent: 'This capture is not running: you are hearing your dry guitar. Reload the page.',
    engineUpdate: (latest: string, current: string) =>
      `Tonecraft Engine ${latest} is available — this computer runs ${current}. Quit it from its icon, then open the new one.`,
    updateEngine: 'Update Tonecraft Engine',
    demo: 'Demo',
    listenDemo: 'Listen to a demo',
    play: 'Play',
    pause: 'Pause',
    loop: 'Loop',
    demoName: 'Demo take (Tonecraft)',
    audioSession: 'Audio session',
    looper: 'Looper',
    loopAction: { empty: 'Rec', recording: 'Stop', playing: 'Overdub', overdubbing: 'Stop', stopped: 'Play' },
    loopStatus: { empty: 'Empty', recording: 'Recording', playing: 'Playing', overdubbing: 'Overdubbing', stopped: 'Stopped' },
    loopNeedsEngine: 'Start the amplifier to use the looper',
    looperOff: 'Looper off',
    looperOffTitle: 'Looper off: erases the loop',
    level: 'Level',
    loopLevel: 'Loop level',
    openTuner: 'Open tuner',
    tuner: 'Tuner',
    startMetronome: 'Start metronome',
    pauseMetronome: 'Pause metronome',
    setTempoFirst: 'Set a tempo first',
    openMetronome: 'Open metronome',
    metronome: 'Metronome',
    closeSettings: 'Close settings',
    audio: 'Audio',
    inputChannel: 'Input channel',
    channels: { follow: 'Auto', left: 'L', right: 'R', sum: 'Both' },
    detecting: 'Detecting inputs…',
    detect: 'Detect audio inputs',
    inputDevice: 'Input device',
    defaultInput: 'Default input',
    input: 'Input',
    outputDevice: 'Output device',
    sameAsInput: 'Same as input',
    output: 'Output',
    done: 'Done',
    // Notices, one sentence of cause and one of remedy.
    detectFailed: 'Unable to detect audio inputs.',
    tunerFailed: 'The tuner could not open.',
    metronomeFailed: 'The metronome could not start. Check the browser audio output.',
    captureFailed: 'That capture did not load. Reload the page; if it persists, run `npm run vendor`.',
    cabUnreadable: (name: string) => `${name} could not be read as an impulse response. A WAV file of the cabinet works.`,
    nativeStopped: (message: string) => `${message}. Start Tonecraft Engine again, or switch the audio engine back to the browser in the settings.`,
    engineFailed: (message: string) => `The amplifier engine did not start (${message}). Reload the page; if it persists, run \`npm run build:dsp\`.`,
    demoMissing: 'The demo take is not installed. It lives in public/di/.',
    pressStart: 'Press start to power the chain.',
    loadAgain: 'Load the file again — stopping released it.',
    nativeFallback: 'Tonecraft Engine is not running, so this is playing in the browser. Start it and choose ASIO again in the audio settings to go back.',
    latencyNative: (input: string, output: string, buffer: number | null) =>
      `${input} ms in and ${output} ms out, as the driver reports them${buffer === null ? '' : ` at ${buffer}-frame buffers`}. The chain itself adds nothing; a smaller buffer in the settings lowers both.`,
    latencyBrowser: (input: string, output: string, selectable: boolean) =>
      `${input} ms of render buffer, which is one block and cannot go lower, and ${output} ms in the output device${selectable ? ', which the Output selector can change' : ''}. The chain itself adds a tenth of a millisecond. The input path is not reported by the browser and is not in this number.`,
    latencyPitch: (ms: string) =>
      ` The transposer is adding ${ms} ms on top: shifting a note means waiting for its waveform to come round again. Switching it off gives that back.`,
  },

  /** A start that failed, as cause and remedy, by the engine's failure kind. */
  failures: {
    'no-input-device': ['No audio input found.', 'Connect an interface and reload.'],
    'permission-denied': ['Microphone access was refused.', 'Allow it in the address bar and reload.'],
    'engine-missing': ['The audio engine is missing.', 'Run `npm run build:dsp` and reload.'],
    'engine-broken': ['The audio engine did not start.', 'Reload the page; if it persists the build is incomplete.'],
    'native-unreachable': ['Tonecraft Engine is not running.', 'Start it, or switch the audio engine back to the browser in the settings.'],
    'native-failed': ['Tonecraft Engine could not open the interface.', 'Check the device in the settings, or close the program that holds it.'],
    unknown: ['The audio engine did not start.', 'Reload the page and try again.'],
  } as Record<EngineFailure['kind'] | 'unknown', readonly [string, string]>,

  /** Messages the engine throws, by their exact English text. */
  engineMessages: {} as Record<string, string>,

  recorder: {
    region: 'Recording and WAV export',
    title: 'Recorder',
    modes: { di: 'DI', processed: 'Processed' },
    modeSmall: { di: 'DI', processed: 'processed' },
    modeGroup: 'Guitar in the export',
    guitar: 'Guitar',
    guitarN: (n: number) => `Guitar ${n}`,
    backing: 'Backing',
    /** The lane's name, in a 96 px column. */
    backingLane: 'Backing',
    listen: 'Listen to take',
    pauseTake: 'Pause take',
    preparing: (p: number) => `Preparing ${p}%`,
    saving: 'Saving…',
    starting: 'Starting…',
    stopRecording: '■ Stop recording',
    newTake: '● New take',
    record: '● Record',
    exporting: (p: number) => `Exporting ${p}%`,
    exportWav: 'Export WAV',
    whatToExport: 'What to export',
    mix: 'Guitar + backing',
    guitarsOnly: 'Guitars only',
    guitarOnly: 'Guitar only',
    trackOnly: (name: string) => `${name} only`,
    backingOnly: 'Backing only',
    cancel: 'Cancel',
    recordInto: (name: string) => `Record into ${name}`,
    trackLevel: (name: string) => `${name} level`,
    backingLevel: 'Backing track level',
    timeline: 'Recording timeline',
    recordedGuitar: 'Recorded guitar',
    recordedGuitarN: (n: number) => `Recorded guitar ${n}`,
    dropOver: 'Press ● Record to play over the other tracks, or drop a DI, or',
    dropFirst: 'Press ● Record to record your guitar, or drop a DI (a dry guitar recording, no amp), or',
    chooseFile: 'choose a file',
    diFile: (name: string) => `${name} DI file`,
    backingTrack: 'Backing track',
    backingWaveform: 'Backing track waveform',
    dropSong: 'Drop a song to play along to, or',
    backingFile: 'Backing track file',
    addTrack: 'Add track',
    cut: 'Cut',
    undoCut: 'Undo cut',
    undoMove: 'Undo move',
    moveTrack: (name: string) => `Move ${name} along the timeline`,
    pressAgain: 'Press again to delete',
    deleteTrack: (name: string) => `Delete ${name}`,
    deleteTake: 'Delete take',
    stopPreview: '■ Stop',
    preview: '▶ Preview',
    replace: 'Replace',
    replaceBacking: 'Replace backing track',
    removeBacking: 'Remove backing track',
    sync: 'Sync',
    guitarSync: 'Guitar sync',
    measured: (ms: number) => `Measured ${ms} ms`,
    selection: (from: string, to: string) => `Selection ${from}–${to}`,
    clearSelection: 'Clear selection',
    playbackFailed: 'Playback failed.',
    chooseGuitarAudio: 'Choose an audio file for the guitar.',
    undecodable: 'That file could not be decoded.',
    chooseBackingAudio: 'Choose an audio file for the backing track.',
    engineStopped: 'The recording engine stopped.',
    rateMismatch: (rate: number | null, current: number | null) =>
      `The other tracks are at ${rate} Hz and the interface runs at ${current} Hz. Set it back to ${rate} Hz to record over them.`,
    cannotStart: 'Could not start recording.',
    cannotSave: 'Could not save the recording.',
    exportFailed: 'Export failed.',
  },

  reader: {
    region: 'Tab reader',
    eyebrow: 'Practice',
    title: 'Tab reader',
    write: 'Write a tab',
    closeEditor: 'Close editor',
    opening: 'Opening…',
    openAnother: 'Open another tab',
    import: 'Import tab',
    importLabel: 'Import tablature',
    dropFile: 'Drop a tablature file',
    cancelCue: 'Cancel synced start',
    pauseTab: 'Pause tablature',
    playTab: 'Play tablature',
    stopTab: 'Stop tablature',
    position: 'Playback position',
    syncedTitle: 'Synced to the metronome',
    synced: (bpm: number) => `Sync · ${bpm} BPM`,
    speed: 'Speed',
    speedLabel: 'Playback speed',
    loopSelection: 'Loop selection',
    loopSong: 'Loop song',
    clearSelection: 'Clear selection',
    volume: 'Volume',
    volumeLabel: 'Tab playback volume',
    view: 'View',
    viewLabel: 'Notation view',
    viewTab: 'Tab',
    viewBoth: 'Score + tab',
    zoom: 'Zoom',
    zoomLabel: 'Tab zoom',
    editor: 'Tab editor',
    bpm: 'BPM',
    tempo: 'Tempo',
    time: 'Time',
    signature: 'Time signature',
    duration: 'Duration',
    dotted: 'Dotted',
    rest: 'Rest',
    deleteKey: 'Delete',
    deleteNote: 'Delete note',
    backspaceKey: 'Backspace',
    deleteBeat: 'Delete beat',
    strings: 'Strings',
    stringCount: 'String count',
    tuning: 'Tuning',
    addTrack: '+ Track',
    deleteTrack: 'Delete track',
    exportGp: 'Export .gp',
    scoreTracks: 'Score tracks',
    tracks: (n: number) => (n === 1 ? '1 track' : `${n} tracks`),
    trackN: (n: number) => `Track ${n}`,
    soloFlag: 'S',
    muteFlag: 'M',
    soloTitle: 'Solo',
    mutedTitle: 'Muted',
    barsWithNotes: (n: number, of: number) => `${n} of ${of} bars have notes`,
    volumeOf: (name: string) => `Volume of ${name}`,
    solo: 'Solo',
    mute: 'Mute',
    firstBar: 'Go to its first bar',
    bars: (n: number) => `${n} bars`,
    scale: 'Scale',
    key: 'Key',
    scaleKey: 'Scale key',
    none: 'None',
    scaleNotes: 'Notes of the scale',
    root: 'Root',
    scaleTone: 'Scale',
    playing: 'Playing',
    untitled: 'Untitled',
    noSynth: 'Playback is unavailable: the synthesizer did not start.',
    unavailable: (why: string) => `Playback is unavailable: ${why}.`,
    instrumentsFailed: 'the instruments did not load',
    unsupported: 'Choose a Guitar Pro, MusicXML, Capella or alphaTex file.',
    sessionOnly: 'Opened for this session. Browser storage is unavailable.',
    cannotOpen: (name: string) => `Could not open ${name}: the file may be damaged or unsupported.`,
    editorFailed: 'The editor could not start.',
    scaleGroups: { Essentials: 'Essentials', Modes: 'Modes', Colours: 'Colours' } as Record<string, string>,
    scales: {
      major: 'Major', 'natural-minor': 'Natural minor', 'minor-pentatonic': 'Minor pentatonic', 'major-pentatonic': 'Major pentatonic',
      blues: 'Blues', 'major-blues': 'Major blues', 'harmonic-minor': 'Harmonic minor', 'melodic-minor': 'Melodic minor',
      dorian: 'Dorian', phrygian: 'Phrygian', lydian: 'Lydian', mixolydian: 'Mixolydian', locrian: 'Locrian',
      'phrygian-dominant': 'Phrygian dominant', 'hungarian-minor': 'Hungarian minor', 'whole-tone': 'Whole tone',
      'diminished-half-whole': 'Diminished (half-whole)', 'diminished-whole-half': 'Diminished (whole-half)',
    } as Record<string, string>,
    tuningName: (name: string) => name,
  },

  engine: {
    audioEngine: 'Audio engine',
    browser: 'Browser',
    native: 'Native',
    asioHint: 'An interface with an ASIO driver plays with less delay through ASIO: choose it above.',
    safariCause: 'Safari cannot reach Tonecraft Engine.',
    safariFix: 'Use Chrome, Edge or Firefox for ASIO.',
    running: (version: string) => `Tonecraft Engine ${version} is running: the sound leaves through it.`,
    updateAvailable: (version: string) => `Version ${version} is available. Quit the engine from its icon, then open the new one.`,
    update: 'Update Tonecraft Engine',
    driver: 'Driver',
    readingDevices: 'Reading devices…',
    noDeviceCause: 'No device answers on this driver.',
    noDeviceFix: 'Connect the interface, or choose another driver.',
    interface: 'Interface',
    inputDevice: 'Input device',
    outputDevice: 'Output device',
    buffer: 'Buffer',
    interfaceSetting: 'Interface setting',
    smallest: (frames: number, ms: string) => `Smallest — ${frames} frames, ${ms} ms`,
    frames: (frames: number, ms: string) => `${frames} frames — ${ms} ms`,
    sampleRate: 'Sample rate',
    deviceDefault: 'Device default',
    inputs: 'Inputs',
    outputs: 'Outputs',
    headphones: (percent: number) => `Headphones — ${percent}%`,
    headphoneLevel: 'Headphone level',
    playingAt: (rate: string, buffer: number | null, input: string, output: string) =>
      `Playing at ${rate} kHz${buffer === null ? '' : ` with ${buffer}-frame buffers`}: ${input} ms in, ${output} ms out.`,
    looking: 'Looking for Tonecraft Engine on this computer…',
    needsWindows: 'ASIO needs Tonecraft Engine',
    needs: 'This needs Tonecraft Engine',
    guide: (needs: string, driver: string, windows: boolean) =>
      `${needs}: a small free program that plays through ${driver} directly${windows ? ', at the buffer set in your interface’s control panel' : ', with the smallest buffer it allows'}. It sits as an icon by the clock; everything is set from here, and the tone is the same.`,
    drivers: { windows: 'your interface’s ASIO driver', macos: 'CoreAudio', linux: 'ALSA', other: 'your system’s audio driver' },
    download: 'Download Tonecraft Engine',
    downloadFor: (system: string) => `Download Tonecraft Engine for ${system}`,
    stepWindowsBefore: 'Unzip it and open',
    stepWindowsAfter: '. If Windows SmartScreen stops it, choose More info, then Run anyway.',
    stepMacBefore: 'Unzip it, then Control-click',
    stepMacAfter: ' and choose Open: macOS asks once, because the program is not notarised. Allow the microphone when asked — that is how it hears the interface.',
    stepLinuxBefore: 'Extract it and run',
    stepLinuxAfter: '.',
    stepConnect: 'Keep this sheet open: it connects by itself. If the browser asks to reach devices on your local network, allow it — that is this page talking to the program on this computer, nothing else.',
    otherVersions: 'Other systems and versions',
    stayInBrowser: 'Keep playing in the browser',
  },

  metronome: {
    dialog: 'Metronome',
    close: 'Close metronome',
    bpm: 'BPM',
    tempo: 'Tempo in BPM',
    tap: 'Tap',
    taps: (n: number) => `${n} of 4 taps`,
    syncTitle: 'Tab bars start on the first beat, at this tempo',
    sync: 'Sync tab',
    volume: 'Volume',
    volumeLabel: 'Metronome volume',
  },

  tuner: {
    dialog: 'Tuner',
    close: 'Close tuner',
    accuracy: 'Tuning accuracy',
    low: 'Low',
    high: 'High',
    inTune: 'In tune',
    tuneUp: 'Tune up',
    tuneDown: 'Tune down',
    waiting: 'Waiting for a note',
    reading: (note: string, cents: number, direction: string) => `${note}, ${cents} cents, ${direction}`,
    cents: (cents: string) => `${cents} cents`,
  },

  meter: {
    input: 'Input level',
    level: 'Level',
    clipping: 'Clipping',
    silent: 'No signal',
    sweet: ', in the sweet spot',
    low: ', low',
    hot: ', hot',
  },

  waveform: { position: 'Position in the file' },

  tourFigure: { lead: 'Lead', rhythm: 'Rhythm', bass: 'Bass', solo: 'Solo', mute: 'Mute', tuning: 'E standard' },
};

export type Ui = typeof en;

const fr: Ui = {
  params: {
    in_trim: 'Entrée', gate_threshold: 'Gate', out_master: 'Sortie',
    tone_bass: 'Graves', tone_mid: 'Médiums', tone_treble: 'Aigus', tone_presence: 'Présence',
    pitch_shift: 'Transpo', pitch_mix: 'Mix', drive_gain: 'Gain', drive_tone: 'Couleur', reverb_mix: 'Mix',
    doubler_spread: 'Doubleur',
  },

  rig: {
    globalControls: 'Réglages généraux',
    home: 'Retour à l’accueil',
    modeLabel: 'Mode',
    modes: { tone: 'Son', play: 'Jeu' },
    modeTitles: { tone: 'L’ampli, pour régler le son', play: 'La tab, pour jouer dessus' },
    transport: 'Transport',
    tab: 'Tab',
    openTab: 'Ouvrir une tab',
    bar: 'Mesure',
    tracks: 'Pistes',
    practice: 'Travail',
    tools: 'Outils',
    levels: 'Niveaux',
    tabLevel: 'Tab',
    take: 'Prise',
    recordTake: 'Enregistrer une prise',
    stopTake: 'Arrêter la prise',
    showRecorder: 'Afficher les prises',
    hideRecorder: 'Masquer les prises',
    meterIn: 'Ent',
    meterOut: 'Sort',
    gateEnabled: 'Gate activé',
    gateOn: 'Gate activé',
    gateOff: 'Gate désactivé',
    doublerEnabled: 'Doubleur activé',
    doublerOn: 'Doubleur activé : une deuxième prise dans l’oreille droite, en retard d’au plus ce nombre de millisecondes',
    doublerOff: 'Doubleur désactivé : la même guitare dans les deux oreilles',
    amplifier: 'Ampli',
    cabinet: 'Baffle',
    capture: 'Capture',
    cabinetIrFile: 'Fichier IR de baffle',
    loadIr: 'Charger une IR…',
    tonePreset: 'Preset de son',
    customTone: 'Son personnalisé',
    previousPreset: 'Preset précédent',
    nextPreset: 'Preset suivant',
    presets: { Lead: 'Lead', 'Modern metal': 'Metal moderne', Clean: 'Clair' },
    myTones: 'Mes sons',
    manageTones: 'Gérer',
    saveTone: 'Sauvegarder ce son…',
    deleteTone: (name: string) => `Supprimer « ${name} »`,
    toneName: 'Nom du son',
    saveToneConfirm: 'Sauvegarder',
    replaceTone: 'Remplacer',
    cancelTone: 'Annuler',
    toneNotKept: 'Ce navigateur ne garde rien : ce son disparaîtra à la fermeture de la page.',
    cabs: {
      v30mod: 'V30 4x12 — Moderne', v30dark: 'V30 4x12 — Hors axe', green: 'Greenback 4x12 — Vintage', mod112: '1x12 dos ouvert',
    },
    guiltAmp: 'Ampli GUILT',
    neutralAmp: 'Ampli Tonecraft',
    glassAlt: 'Vitrail gothique violet avec une rosace centrale',
    neutralMotto: 'TROUVEZ VOTRE FRÉQUENCE',
    leadAmplifier: 'AMPLI LEAD',
    captureSeries: 'SÉRIE CAPTURE',
    groups: { tone: 'Timbre', pitch: 'Hauteur', boost: 'Boost', reverb: 'Réverb' },
    groupEnabled: { tone: 'Timbre activé', pitch: 'Hauteur activée', boost: 'Boost activé', reverb: 'Réverb activée' },
    pedals: 'Pédales',
    on: 'Activé',
    off: 'Désactivé',
    power: 'Marche',
    amplifierPower: 'Mise en marche de l’ampli',
    captureSilent: 'Cette capture ne tourne pas : vous entendez votre guitare sans ampli. Rechargez la page.',
    engineUpdate: (latest, current) =>
      `Tonecraft Engine ${latest} est disponible — cet ordinateur a la version ${current}. Quittez-le depuis son icône, puis ouvrez la nouvelle.`,
    updateEngine: 'Mettre à jour Tonecraft Engine',
    demo: 'Démo',
    listenDemo: 'Écouter une démo',
    play: 'Lecture',
    pause: 'Pause',
    loop: 'En boucle',
    demoName: 'Prise de démo (Tonecraft)',
    audioSession: 'Session audio',
    looper: 'Looper',
    loopAction: { empty: 'Enr.', recording: 'Stop', playing: 'Ajouter', overdubbing: 'Stop', stopped: 'Lecture' },
    loopStatus: { empty: 'Vide', recording: 'Enregistrement', playing: 'Lecture', overdubbing: 'Ajout', stopped: 'Arrêté' },
    loopNeedsEngine: 'Allumez l’ampli pour utiliser le looper',
    looperOff: 'Éteindre le looper',
    looperOffTitle: 'Éteindre le looper : efface la boucle',
    level: 'Niveau',
    loopLevel: 'Niveau de la boucle',
    openTuner: 'Ouvrir l’accordeur',
    tuner: 'Accordeur',
    startMetronome: 'Lancer le métronome',
    pauseMetronome: 'Mettre le métronome en pause',
    setTempoFirst: 'Réglez d’abord un tempo',
    openMetronome: 'Ouvrir le métronome',
    metronome: 'Métronome',
    closeSettings: 'Fermer les réglages',
    audio: 'Audio',
    inputChannel: 'Canal d’entrée',
    channels: { follow: 'Auto', left: 'G', right: 'D', sum: 'Les deux' },
    detecting: 'Détection des entrées…',
    detect: 'Détecter les entrées audio',
    inputDevice: 'Périphérique d’entrée',
    defaultInput: 'Entrée par défaut',
    input: 'Entrée',
    outputDevice: 'Périphérique de sortie',
    sameAsInput: 'Comme l’entrée',
    output: 'Sortie',
    done: 'Terminé',
    detectFailed: 'Impossible de détecter les entrées audio.',
    tunerFailed: 'L’accordeur n’a pas pu s’ouvrir.',
    metronomeFailed: 'Le métronome n’a pas pu démarrer. Vérifiez la sortie audio du navigateur.',
    captureFailed: 'Cette capture ne s’est pas chargée. Rechargez la page ; si ça persiste, lancez `npm run vendor`.',
    cabUnreadable: (name) => `${name} n’a pas pu être lu comme une réponse impulsionnelle. Un fichier WAV du baffle fonctionne.`,
    nativeStopped: (message) => `${message}. Relancez Tonecraft Engine, ou repassez le moteur audio sur le navigateur dans les réglages.`,
    engineFailed: (message) => `Le moteur de l’ampli n’a pas démarré (${message}). Rechargez la page ; si ça persiste, lancez \`npm run build:dsp\`.`,
    demoMissing: 'La prise de démo n’est pas installée. Elle se trouve dans public/di/.',
    pressStart: 'Allumez l’ampli pour alimenter la chaîne.',
    loadAgain: 'Rechargez le fichier — l’arrêt l’a libéré.',
    nativeFallback: 'Tonecraft Engine ne tourne pas : le son passe par le navigateur. Lancez-le et rechoisissez ASIO dans les réglages audio pour y revenir.',
    latencyNative: (input, output, buffer) =>
      `${input} ms en entrée et ${output} ms en sortie, tels que le pilote les annonce${buffer === null ? '' : `, avec des buffers de ${buffer} échantillons`}. La chaîne elle-même n’ajoute rien ; un buffer plus petit dans les réglages baisse les deux.`,
    latencyBrowser: (input, output, selectable) =>
      `${input} ms de buffer de rendu, soit un bloc, impossible à réduire, et ${output} ms dans le périphérique de sortie${selectable ? ', que le choix de sortie peut changer' : ''}. La chaîne elle-même ajoute un dixième de milliseconde. Le chemin d’entrée n’est pas annoncé par le navigateur et n’est pas compté.`,
    latencyPitch: (ms) =>
      ` Le transpositeur ajoute ${ms} ms : décaler une note oblige à attendre que sa forme d’onde revienne. L’éteindre les rend.`,
  },

  failures: {
    'no-input-device': ['Aucune entrée audio trouvée.', 'Branchez une interface et rechargez.'],
    'permission-denied': ['L’accès au micro a été refusé.', 'Autorisez-le dans la barre d’adresse et rechargez.'],
    'engine-missing': ['Le moteur audio est absent.', 'Lancez `npm run build:dsp` et rechargez.'],
    'engine-broken': ['Le moteur audio n’a pas démarré.', 'Rechargez la page ; si ça persiste, le build est incomplet.'],
    'native-unreachable': ['Tonecraft Engine ne tourne pas.', 'Lancez-le, ou repassez le moteur audio sur le navigateur dans les réglages.'],
    'native-failed': ['Tonecraft Engine n’a pas pu ouvrir l’interface.', 'Vérifiez le périphérique dans les réglages, ou fermez le programme qui l’occupe.'],
    unknown: ['Le moteur audio n’a pas démarré.', 'Rechargez la page et réessayez.'],
  },

  engineMessages: {
    'Invalid saved take.': 'La prise enregistrée est invalide.',
    'Invalid recording.': 'L’enregistrement est invalide.',
    'The recording contains invalid samples.': 'L’enregistrement contient des échantillons invalides.',
    'Export cancelled.': 'Export annulé.',
    'Audio export failed. Please try again.': 'L’export audio a échoué. Réessayez.',
    'Choose an amplifier before exporting the processed take.': 'Choisissez un ampli avant d’exporter la prise traitée.',
    'The amplifier could not be loaded.': 'L’ampli n’a pas pu être chargé.',
    'The audio engine or amplifier could not be loaded for export.': 'Le moteur audio ou l’ampli n’a pas pu être chargé pour l’export.',
    'There is nothing to export in this selection.': 'Il n’y a rien à exporter dans cette sélection.',
    'Start the audio engine before recording.': 'Allumez le moteur audio avant d’enregistrer.',
    'A recording is already running.': 'Un enregistrement est déjà en cours.',
    'Recording could not start.': 'L’enregistrement n’a pas pu démarrer.',
    'The audio engine stopped before the take could be saved.': 'Le moteur audio s’est arrêté avant que la prise soit enregistrée.',
    'The recording is empty.': 'L’enregistrement est vide.',
    'The recorded audio could not be retrieved.': 'L’audio enregistré n’a pas pu être récupéré.',
    'Tonecraft Engine closed': 'Tonecraft Engine s’est fermé',
    'Tonecraft Engine stopped': 'Tonecraft Engine s’est arrêté',
  },

  recorder: {
    region: 'Enregistrement et export WAV',
    title: 'Enregistreur',
    modes: { di: 'DI', processed: 'Traité' },
    modeSmall: { di: 'DI', processed: 'traité' },
    modeGroup: 'Guitare dans l’export',
    guitar: 'Guitare',
    guitarN: (n) => `Guitare ${n}`,
    backing: 'Accompagnement',
    backingLane: 'Accomp.',
    listen: 'Écouter la prise',
    pauseTake: 'Mettre la prise en pause',
    preparing: (p) => `Préparation ${p} %`,
    saving: 'Enregistrement…',
    starting: 'Démarrage…',
    stopRecording: '■ Arrêter l’enregistrement',
    newTake: '● Nouvelle prise',
    record: '● Enregistrer',
    exporting: (p) => `Export ${p} %`,
    exportWav: 'Exporter en WAV',
    whatToExport: 'Que faut-il exporter',
    mix: 'Guitare + accompagnement',
    guitarsOnly: 'Guitares seules',
    guitarOnly: 'Guitare seule',
    trackOnly: (name) => `${name} seule`,
    backingOnly: 'Accompagnement seul',
    cancel: 'Annuler',
    recordInto: (name) => `Enregistrer sur ${name}`,
    trackLevel: (name) => `Niveau de ${name}`,
    backingLevel: 'Niveau de l’accompagnement',
    timeline: 'Timeline d’enregistrement',
    recordedGuitar: 'Guitare enregistrée',
    recordedGuitarN: (n) => `Guitare enregistrée ${n}`,
    dropOver: 'Appuyez sur ● Enregistrer pour jouer par-dessus les autres pistes, déposez un DI, ou',
    dropFirst: 'Appuyez sur ● Enregistrer pour enregistrer votre guitare, déposez un DI (une guitare enregistrée sans ampli), ou',
    chooseFile: 'choisissez un fichier',
    diFile: (name) => `Fichier DI de ${name}`,
    backingTrack: 'Accompagnement',
    backingWaveform: 'Forme d’onde de l’accompagnement',
    dropSong: 'Déposez un morceau pour jouer dessus, ou',
    backingFile: 'Fichier d’accompagnement',
    addTrack: 'Ajouter une piste',
    cut: 'Couper',
    undoCut: 'Annuler la coupe',
    undoMove: 'Annuler le déplacement',
    moveTrack: (name) => `Déplacer ${name} sur la timeline`,
    pressAgain: 'Appuyez encore pour supprimer',
    deleteTrack: (name) => `Supprimer ${name}`,
    deleteTake: 'Supprimer la prise',
    stopPreview: '■ Stop',
    preview: '▶ Pré-écoute',
    replace: 'Remplacer',
    replaceBacking: 'Remplacer l’accompagnement',
    removeBacking: 'Retirer l’accompagnement',
    sync: 'Synchro',
    guitarSync: 'Synchro de la guitare',
    measured: (ms) => `Mesuré ${ms} ms`,
    selection: (from, to) => `Sélection ${from}–${to}`,
    clearSelection: 'Effacer la sélection',
    playbackFailed: 'La lecture a échoué.',
    chooseGuitarAudio: 'Choisissez un fichier audio pour la guitare.',
    undecodable: 'Ce fichier n’a pas pu être décodé.',
    chooseBackingAudio: 'Choisissez un fichier audio pour l’accompagnement.',
    engineStopped: 'Le moteur d’enregistrement s’est arrêté.',
    rateMismatch: (rate, current) =>
      `Les autres pistes sont à ${rate} Hz et l’interface tourne à ${current} Hz. Remettez-la à ${rate} Hz pour enregistrer par-dessus.`,
    cannotStart: 'L’enregistrement n’a pas pu démarrer.',
    cannotSave: 'L’enregistrement n’a pas pu être sauvegardé.',
    exportFailed: 'L’export a échoué.',
  },

  reader: {
    region: 'Lecteur de tablatures',
    eyebrow: 'Pratique',
    title: 'Lecteur de tablatures',
    write: 'Écrire une tab',
    closeEditor: 'Fermer l’éditeur',
    opening: 'Ouverture…',
    openAnother: 'Ouvrir une autre tab',
    import: 'Importer une tab',
    importLabel: 'Importer une tablature',
    dropFile: 'Déposer un fichier de tablature',
    cancelCue: 'Annuler le départ synchronisé',
    pauseTab: 'Mettre la tablature en pause',
    playTab: 'Lire la tablature',
    stopTab: 'Arrêter la tablature',
    position: 'Position de lecture',
    syncedTitle: 'Synchronisé au métronome',
    synced: (bpm) => `Synchro · ${bpm} BPM`,
    speed: 'Vitesse',
    speedLabel: 'Vitesse de lecture',
    loopSelection: 'Boucler la sélection',
    loopSong: 'Boucler le morceau',
    clearSelection: 'Effacer la sélection',
    volume: 'Volume',
    volumeLabel: 'Volume de la tablature',
    view: 'Vue',
    viewLabel: 'Vue de la notation',
    viewTab: 'Tab',
    viewBoth: 'Partition + tab',
    zoom: 'Zoom',
    zoomLabel: 'Zoom de la tab',
    editor: 'Éditeur de tab',
    bpm: 'BPM',
    tempo: 'Tempo',
    time: 'Mesure',
    signature: 'Signature rythmique',
    duration: 'Durée',
    dotted: 'Pointée',
    rest: 'Silence',
    deleteKey: 'Suppr',
    deleteNote: 'Supprimer la note',
    backspaceKey: 'Retour arrière',
    deleteBeat: 'Supprimer le temps',
    strings: 'Cordes',
    stringCount: 'Nombre de cordes',
    tuning: 'Accordage',
    addTrack: '+ Piste',
    deleteTrack: 'Supprimer la piste',
    exportGp: 'Exporter en .gp',
    scoreTracks: 'Pistes de la partition',
    tracks: (n) => (n === 1 ? '1 piste' : `${n} pistes`),
    trackN: (n) => `Piste ${n}`,
    soloFlag: 'S',
    muteFlag: 'M',
    soloTitle: 'Solo',
    mutedTitle: 'Muette',
    barsWithNotes: (n, of) => `${n} mesures sur ${of} ont des notes`,
    volumeOf: (name) => `Volume de ${name}`,
    solo: 'Solo',
    mute: 'Muet',
    firstBar: 'Aller à sa première mesure',
    bars: (n) => `${n} mesures`,
    scale: 'Gamme',
    key: 'Tonique',
    scaleKey: 'Tonique de la gamme',
    none: 'Aucune',
    scaleNotes: 'Notes de la gamme',
    root: 'Tonique',
    scaleTone: 'Gamme',
    playing: 'Jouée',
    untitled: 'Sans titre',
    noSynth: 'Lecture indisponible : le synthétiseur n’a pas démarré.',
    unavailable: (why) => `Lecture indisponible : ${why}.`,
    instrumentsFailed: 'les instruments ne se sont pas chargés',
    unsupported: 'Choisissez un fichier Guitar Pro, MusicXML, Capella ou alphaTex.',
    sessionOnly: 'Ouvert pour cette session. Le stockage du navigateur est indisponible.',
    cannotOpen: (name) => `Impossible d’ouvrir ${name} : le fichier est peut-être abîmé ou non pris en charge.`,
    editorFailed: 'L’éditeur n’a pas pu démarrer.',
    scaleGroups: { Essentials: 'Essentielles', Modes: 'Modes', Colours: 'Couleurs' },
    scales: {
      major: 'Majeure', 'natural-minor': 'Mineure naturelle', 'minor-pentatonic': 'Pentatonique mineure', 'major-pentatonic': 'Pentatonique majeure',
      blues: 'Blues', 'major-blues': 'Blues majeur', 'harmonic-minor': 'Mineure harmonique', 'melodic-minor': 'Mineure mélodique',
      dorian: 'Dorien', phrygian: 'Phrygien', lydian: 'Lydien', mixolydian: 'Mixolydien', locrian: 'Locrien',
      'phrygian-dominant': 'Phrygien dominant', 'hungarian-minor': 'Mineure hongroise', 'whole-tone': 'Par tons',
      'diminished-half-whole': 'Diminuée (demi-ton, ton)', 'diminished-whole-half': 'Diminuée (ton, demi-ton)',
    },
    tuningName: (name) => name.replace(/^Bass /, 'Basse '),
  },

  engine: {
    audioEngine: 'Moteur audio',
    browser: 'Navigateur',
    native: 'Natif',
    asioHint: 'Une interface avec un pilote ASIO joue avec moins de délai en ASIO : choisissez-le ci-dessus.',
    safariCause: 'Safari ne peut pas joindre Tonecraft Engine.',
    safariFix: 'Utilisez Chrome, Edge ou Firefox pour l’ASIO.',
    running: (version) => `Tonecraft Engine ${version} tourne : le son sort par lui.`,
    updateAvailable: (version) => `La version ${version} est disponible. Quittez le moteur depuis son icône, puis ouvrez la nouvelle.`,
    update: 'Mettre à jour Tonecraft Engine',
    driver: 'Pilote',
    readingDevices: 'Lecture des périphériques…',
    noDeviceCause: 'Aucun périphérique ne répond sur ce pilote.',
    noDeviceFix: 'Branchez l’interface, ou choisissez un autre pilote.',
    interface: 'Interface',
    inputDevice: 'Périphérique d’entrée',
    outputDevice: 'Périphérique de sortie',
    buffer: 'Buffer',
    interfaceSetting: 'Réglage de l’interface',
    smallest: (frames, ms) => `Le plus petit — ${frames} échantillons, ${ms} ms`,
    frames: (frames, ms) => `${frames} échantillons — ${ms} ms`,
    sampleRate: 'Fréquence d’échantillonnage',
    deviceDefault: 'Par défaut du périphérique',
    inputs: 'Entrées',
    outputs: 'Sorties',
    headphones: (percent) => `Casque — ${percent} %`,
    headphoneLevel: 'Niveau du casque',
    playingAt: (rate, buffer, input, output) =>
      `Lecture à ${rate} kHz${buffer === null ? '' : ` avec des buffers de ${buffer} échantillons`} : ${input} ms en entrée, ${output} ms en sortie.`,
    looking: 'Recherche de Tonecraft Engine sur cet ordinateur…',
    needsWindows: 'L’ASIO passe par Tonecraft Engine',
    needs: 'Il faut Tonecraft Engine',
    guide: (needs, driver, windows) =>
      `${needs} : un petit programme gratuit qui joue directement via ${driver}${windows ? ', avec le buffer réglé dans le panneau de votre interface' : ', avec le plus petit buffer qu’il accepte'}. Il reste en icône près de l’horloge ; tout se règle ici, et le son est le même.`,
    drivers: { windows: 'le pilote ASIO de votre interface', macos: 'CoreAudio', linux: 'ALSA', other: 'le pilote audio de votre système' },
    download: 'Télécharger Tonecraft Engine',
    downloadFor: (system) => `Télécharger Tonecraft Engine pour ${system}`,
    stepWindowsBefore: 'Décompressez-le et ouvrez',
    stepWindowsAfter: '. Si Windows SmartScreen le bloque, choisissez Informations complémentaires, puis Exécuter quand même.',
    stepMacBefore: 'Décompressez-le, puis Ctrl-clic sur',
    stepMacAfter: ' et choisissez Ouvrir : macOS le demande une fois, car le programme n’est pas notarié. Autorisez le micro quand il le demande — c’est ainsi qu’il entend l’interface.',
    stepLinuxBefore: 'Extrayez-le et lancez',
    stepLinuxAfter: '.',
    stepConnect: 'Gardez ce panneau ouvert : il se connecte tout seul. Si le navigateur demande l’accès aux appareils du réseau local, autorisez-le — c’est cette page qui parle au programme sur cet ordinateur, rien d’autre.',
    otherVersions: 'Autres systèmes et versions',
    stayInBrowser: 'Continuer à jouer dans le navigateur',
  },

  metronome: {
    dialog: 'Métronome',
    close: 'Fermer le métronome',
    bpm: 'BPM',
    tempo: 'Tempo en BPM',
    tap: 'Tap',
    taps: (n) => `${n} tap${n > 1 ? 's' : ''} sur 4`,
    syncTitle: 'Les mesures de la tab démarrent sur le premier temps, à ce tempo',
    sync: 'Synchro tab',
    volume: 'Volume',
    volumeLabel: 'Volume du métronome',
  },

  tuner: {
    dialog: 'Accordeur',
    close: 'Fermer l’accordeur',
    accuracy: 'Justesse',
    low: 'Bas',
    high: 'Haut',
    inTune: 'Juste',
    tuneUp: 'Remontez',
    tuneDown: 'Descendez',
    waiting: 'En attente d’une note',
    reading: (note, cents, direction) => `${note}, ${cents} cents, ${direction}`,
    cents: (cents) => `${cents} cents`,
  },

  meter: {
    input: 'Niveau d’entrée',
    level: 'Niveau',
    clipping: 'Saturation',
    silent: 'Pas de signal',
    sweet: ', dans la bonne zone',
    low: ', faible',
    hot: ', fort',
  },

  waveform: { position: 'Position dans le fichier' },

  tourFigure: { lead: 'Lead', rhythm: 'Rythmique', bass: 'Basse', solo: 'Solo', mute: 'Muet', tuning: 'E standard' },
};

export const UI = { en, fr } as const;
