/**
 * Generates `dsp/chain.generated.h` from `params.ts` and `chain.ts` (AD-7).
 *
 * The C++ chain addresses parameters by wire index and fills a meter frame by
 * index. Both lists live in TypeScript, and a hand-copied C++ enum would drift
 * from them the first time someone appended a parameter and forgot the other
 * file — silently, because a wrong index is still a valid index. So the header
 * is written from the schema, and `npm run check` fails when the committed one
 * no longer matches what this produces.
 *
 * Usage:  npm run generate
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PARAMS, STAGES } from './params.ts';
import {
  CHAIN_ABI_VERSION, METERS, STAGE_RMS_OFFSET, STAGE_SLOTS, METER_COUNT,
  IR_SLOTS, CHANNEL_CODES, CLICK_WAVES, LOOP_STATES, LOOP_MAX_SECONDS,
} from './chain.ts';

export const GENERATED_HEADER = join(dirname(fileURLToPath(import.meta.url)), '..', 'dsp', 'chain.generated.h');

const upper = (id: string): string => id.toUpperCase();
/** The schema's own decimal as a float literal: the compiler does the rounding. */
const f32 = (v: number): string => {
  const s = String(v);
  return `${s.includes('.') || s.includes('e') ? s : `${s}.0`}f`;
};

export function generateHeader(): string {
  const lines: string[] = [];
  const out = (s = ''): void => { lines.push(s); };

  out('/* Generated by schema/generate.ts from schema/params.ts and schema/chain.ts.');
  out('   Do not edit: `npm run generate` rewrites it, `npm run check` rejects drift. */');
  out('#pragma once');
  out();
  out(`#define TC_ABI_VERSION ${CHAIN_ABI_VERSION}`);
  out();
  out('/* Parameters, by wire index (AD-8: append-only, never reordered). */');
  out('enum TcParam {');
  PARAMS.forEach((p, i) => out(`  TC_P_${upper(p.id)} = ${i},${p.deprecated === true ? '  /* deprecated */' : ''}`));
  out(`  TC_PARAM_COUNT = ${PARAMS.length}`);
  out('};');
  out();
  out(`static const float TC_PARAM_DEFAULT[TC_PARAM_COUNT] = {\n  ${PARAMS.map((p) => f32(p.default)).join(', ')}\n};`);
  out(`static const float TC_PARAM_MIN[TC_PARAM_COUNT] = {\n  ${PARAMS.map((p) => f32(p.min)).join(', ')}\n};`);
  out(`static const float TC_PARAM_MAX[TC_PARAM_COUNT] = {\n  ${PARAMS.map((p) => f32(p.max)).join(', ')}\n};`);
  out(`static const unsigned char TC_PARAM_DEPRECATED[TC_PARAM_COUNT] = {\n  ${PARAMS.map((p) => (p.deprecated === true ? 1 : 0)).join(', ')}\n};`);
  out();
  out('/* Meter slots, one per stage, by stable id (AD-21). */');
  out('enum TcSlot {');
  for (const s of STAGES) out(`  TC_SLOT_${upper(s.id)} = ${s.meterSlot},`);
  out(`  TC_SLOT_COUNT = ${STAGE_SLOTS}`);
  out('};');
  out();
  out('/* The meter frame, in order (AD-12). */');
  out('enum TcMeter {');
  METERS.forEach((m, i) => out(`  TC_M_${upper(m)} = ${i},`));
  out(`  TC_M_STAGE_RMS = ${STAGE_RMS_OFFSET},`);
  out(`  TC_METER_COUNT = ${METER_COUNT}`);
  out('};');
  out();
  out(`enum TcIrSlot { ${Object.entries(IR_SLOTS).map(([k, v]) => `TC_IR_${upper(k)} = ${v}`).join(', ')} };`);
  out(`enum TcChannel { ${Object.entries(CHANNEL_CODES).map(([k, v]) => `TC_CH_${upper(k)} = ${v}`).join(', ')} };`);
  out(`enum TcWave { ${Object.entries(CLICK_WAVES).map(([k, v]) => `TC_WAVE_${upper(k)} = ${v}`).join(', ')} };`);
  out(`enum TcLoop { ${Object.entries(LOOP_STATES).map(([k, v]) => `TC_LOOP_${upper(k)} = ${v}`).join(', ')} };`);
  out(`#define TC_LOOP_MAX_SECONDS ${f32(LOOP_MAX_SECONDS)}`);
  out();
  return lines.join('\n');
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(GENERATED_HEADER, generateHeader());
  console.log(`generate: wrote ${GENERATED_HEADER}`);
}
