/**
 * Writes `dsp/model/params.generated.h` from `schema/params.ts`.
 *
 * CLAUDE.md section 8: the schema is the single source of truth and the C++
 * header is generated from it, never retyped. A bound that disagrees between
 * the converter and the kernel does not fail the build — it writes a blob the
 * kernel reads with the wrong shape, and a model read with the wrong shape
 * plays, and plays a different amplifier.
 *
 * Usage:  npm run model:header      (run by npm run model:build)
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  BLOCK_FRAMES,
  INTERNAL_SAMPLE_RATE,
  MODEL_MAX_LAYER_ARRAYS,
  MODEL_MAX_LAYERS_PER_ARRAY,
  MODEL_MAX_CHANNELS,
  MODEL_MAX_KERNEL_SIZE,
  MODEL_MAX_DILATION,
  MODEL_MAX_WEIGHTS,
  MODEL_HISTORY_SLACK_BLOCKS,
  MODEL_HISTORY_POOL_FLOATS,
  MODEL_BLOB_MAGIC,
  MODEL_BLOB_VERSION,
} from '../schema/params.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'dsp/model/params.generated.h');

const lines = [
  '// GENERATED by scripts/generate-model-header.ts from schema/params.ts.',
  '// Do not edit. Run `npm run model:header` instead.',
  '#pragma once',
  '',
  '#include <cstdint>',
  '',
  'namespace tonecraft {',
  '',
  `constexpr uint32_t kInternalSampleRate = ${INTERNAL_SAMPLE_RATE};`,
  `constexpr uint32_t kBlockFrames = ${BLOCK_FRAMES};`,
  `constexpr uint32_t kModelMaxLayerArrays = ${MODEL_MAX_LAYER_ARRAYS};`,
  `constexpr uint32_t kModelMaxLayersPerArray = ${MODEL_MAX_LAYERS_PER_ARRAY};`,
  `constexpr uint32_t kModelMaxChannels = ${MODEL_MAX_CHANNELS};`,
  `constexpr uint32_t kModelMaxKernelSize = ${MODEL_MAX_KERNEL_SIZE};`,
  `constexpr uint32_t kModelMaxDilation = ${MODEL_MAX_DILATION};`,
  `constexpr uint32_t kModelMaxWeights = ${MODEL_MAX_WEIGHTS};`,
  `constexpr uint32_t kModelHistorySlackBlocks = ${MODEL_HISTORY_SLACK_BLOCKS};`,
  `constexpr uint32_t kModelHistoryPoolFloats = ${MODEL_HISTORY_POOL_FLOATS};`,
  `constexpr uint32_t kModelBlobMagic = 0x${MODEL_BLOB_MAGIC.toString(16)}u;`,
  `constexpr uint32_t kModelBlobVersion = ${MODEL_BLOB_VERSION};`,
  '',
  '}  // namespace tonecraft',
  '',
];

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'));
console.log(`model: wrote dsp/model/params.generated.h`);
