/* =============================================================================
   scripts/test-landing.mjs — the home page, in a real browser
   -----------------------------------------------------------------------------
   The studio has two end-to-end suites and the page that sells it had none,
   which is backwards: the home page is the one thing every visitor sees, it
   ships 0 kB of JavaScript, and everything that can go wrong with it goes wrong
   quietly. Nothing throws. It just looks dead, or wrong, or ships a font
   nobody asked for.

   Four traps, each of which has actually happened and each of which is a check
   below:

     - **the minifier eats the scroll animations.** `animation-timeline` is not
       part of the `animation` shorthand, so folding the two — which the CSS
       minifier does whenever they sit in one rule — emits
       `animation: linear both reveal view()`, which no engine parses. The whole
       declaration is dropped and every reveal on the page silently stops
       existing. Landing.astro keeps them in separate rules on purpose; this
       asserts the build agrees;
     - **a face that was removed is still fetched.** The studio carries three
       faces and no more. A fourth one left in a rule costs a download on the
       critical path of a page whose whole point is that it has none;
     - **a shot that 404s.** Every picture here is a screenshot generated by
       `npm run shots`; a renamed one leaves a hole nothing else reports;
     - **a line that runs off the side.** The page is read on a phone more
       often than on this machine.

   Prerequisites:
       npm run build
       npx playwright install chromium

   Usage:  npm run test:landing   (starts its own static server)
   ========================================================================== */

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { chromium } from 'playwright';

const dist = path.resolve('dist');
const mime = {
  '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html', '.json': 'application/json',
  '.woff2': 'font/woff2', '.svg': 'image/svg+xml', '.webp': 'image/webp', '.png': 'image/png',
  '.avif': 'image/avif', '.txt': 'text/plain', '.xml': 'application/xml',
};
const server = http.createServer((req, res) => {
  const relative = decodeURIComponent(new URL(req.url, 'http://localhost').pathname).slice(1);
  let file = path.resolve(dist, relative);
  try { if (fs.statSync(file).isDirectory()) file = path.join(file, 'index.html'); } catch { /* not a directory */ }
  if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404); res.end(); return; }
  res.setHeader('Content-Type', mime[path.extname(file)] ?? 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;

/** The three faces DESIGN.md §3 names, and nothing else. */
const FACES = ['anybody', 'onest', 'cormorant-garamond'];

const browser = await chromium.launch();
try {
  /* ---- The built stylesheet, before a browser is asked anything ---------- */
  const styles = fs.readdirSync(path.join(dist, '_astro')).filter(f => f.endsWith('.css'));
  const landingCss = styles
    .map(f => fs.readFileSync(path.join(dist, '_astro', f), 'utf8'))
    .filter(css => css.includes('animation-timeline'))
    .join('\n');
  assert(landingCss.length > 0, 'the built CSS still carries animation-timeline');
  // The shorthand may never carry a timeline: that is the form no engine parses.
  const folded = landingCss.match(/animation:[^;}]*(?:view\(\)|scroll\()[^;}]*/g) ?? [];
  assert.deepEqual(folded, [], 'no animation shorthand was folded with its timeline');
  for (const kind of ['view()', 'scroll(root)']) {
    assert(landingCss.includes(`animation-timeline:${kind}`), `${kind} survives minification`);
  }
  console.log('ok the scroll animations survive the minifier');

  /* ---- Both pages, as a visitor gets them ------------------------------- */
  for (const [tag, url] of [['English', `${origin}/`], ['French', `${origin}/fr/`]]) {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: tag === 'French' ? 'fr-FR' : 'en-US' });
    const errors = [];
    const failed = [];
    const fonts = [];
    page.on('pageerror', e => { errors.push(e.message); console.log('pageerror:', e.stack ?? e.message); });
    page.on('response', r => {
      if (r.status() >= 400) failed.push(`${r.status()} ${r.url()}`);
      if (r.url().endsWith('.woff2')) fonts.push(path.basename(new URL(r.url()).pathname));
    });
    await page.goto(url, { waitUntil: 'networkidle' });

    // 0 kB of JavaScript on the content path: the one inline script that keeps
    // the page in the studio's language is a few hundred bytes and is inline.
    const modules = await page.evaluate(() => [...document.querySelectorAll('script[src]')].map(s => s.getAttribute('src')));
    assert.deepEqual(modules, [], `${tag}: the home page loads no script`);

    // Every picture resolves and has actually decoded. Walked down the page
    // first: all but the hero are `loading="lazy"`, so a shot that 404s three
    // screens down is not even requested until something scrolls past it.
    const bottom = await page.evaluate(() => document.body.scrollHeight);
    for (let y = 0; y <= bottom; y += 700) {
      await page.evaluate(t => window.scrollTo(0, t), y);
      await page.waitForTimeout(60);
    }
    await page.waitForLoadState('networkidle');
    const blank = await page.evaluate(() => [...document.images]
      .filter(i => i.complete && i.naturalWidth === 0)
      .map(i => i.currentSrc || i.src));
    assert.deepEqual(blank, [], `${tag}: every picture on the page decoded`);
    const pictures = await page.evaluate(() => document.images.length);
    assert(pictures >= 10, `${tag}: the page still carries its shots (${pictures})`);
    assert.deepEqual(failed, [], `${tag}: nothing on the page 404s`);

    // The faces, by what the browser actually fetched.
    const unknown = fonts.filter(f => !FACES.some(face => f.startsWith(face)));
    assert.deepEqual(unknown, [], `${tag}: only the three faces are fetched (${fonts.join(', ')})`);

    // Back to the top: a plain anchor, so it works with no script at all.
    await page.evaluate(() => window.scrollTo(0, 4000));
    await page.waitForTimeout(400);
    const shown = await page.locator('.to-top').evaluate(el => getComputedStyle(el).visibility);
    assert.equal(shown, 'visible', `${tag}: the way back up appears once the page is scrolled`);
    await page.locator('.to-top').click();
    await page.waitForTimeout(700);
    assert.equal(await page.evaluate(() => Math.round(scrollY)), 0, `${tag}: and goes all the way up`);

    // Nothing runs off the side, at the three widths the page is read at. The
    // banner's own picture is scaled past its frame on purpose and clipped by
    // it, so the document's scroll width is what is asked, not each box.
    for (const [width, height] of [[390, 844], [834, 1112], [1440, 1000]]) {
      await page.setViewportSize({ width, height });
      await page.waitForTimeout(300);
      const wide = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth);
      assert(wide <= 1, `${tag}: no horizontal overflow at ${width}px (${wide}px over)`);
    }

    assert.deepEqual(errors, [], `${tag}: nothing threw`);
    await page.close();
    console.log(`ok the ${tag} home page: no script, no 404, three faces, no overflow`);
  }

  /* ---- The two pages point at each other, and at the studio ------------- */
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: 'en-US' });
  await page.goto(`${origin}/`, { waitUntil: 'networkidle' });
  const links = await page.evaluate(() => ({
    canonical: document.querySelector('link[rel=canonical]')?.getAttribute('href') ?? null,
    alternates: [...document.querySelectorAll('link[rel=alternate][hreflang]')].map(l => l.getAttribute('hreflang')).sort(),
    studio: [...document.querySelectorAll('a[href*="/app/"]')].length,
    // One block holding an array, so each entry is read rather than the block.
    jsonLd: [...document.querySelectorAll('script[type="application/ld+json"]')]
      .flatMap(s => [JSON.parse(s.textContent)].flat())
      .map(entry => entry['@type']),
  }));
  assert(links.canonical !== null, 'the page carries a canonical');
  // FR/EN from the first day, and hreflang correct on every page (CLAUDE.md §6).
  assert(links.alternates.includes('en') && links.alternates.includes('fr'), `both languages are declared (${links.alternates.join(', ')})`);
  assert(links.studio > 0, 'the page leads to the studio');
  assert(links.jsonLd.includes('SoftwareApplication'), `the home page carries its JSON-LD (${links.jsonLd.join(', ')})`);
  await page.close();
  console.log('ok the home page is indexable: canonical, hreflang, JSON-LD, a way in');
} finally {
  await browser.close();
  server.close();
}
